Add option to use a directory or file pattern instead of a file list
This patch adds a "-d" option to specify a directory or file mask pattern.
You can use -d /etc/ssl/ to check ALL files in /etc/ssl or e.g.
-d "/etc/letsencrypt/certs/*/*.pem" to check all pem files according to
the pattern. This allows to check all certificates created by Let's
Encrypt Clients (like dehydrated) without creating and updating a file
list. Symbolic links will be followed.

diff --git a/ssl-cert-check b/ssl-cert-check
--- a/ssl-cert-check
+++ b/ssl-cert-check
@@ -15,6 +15,7 @@
 # Version 3.30
 #  - Use highest returncode for Nagios output -- Marcel Pennewiss
 #  - Set RETCODE to 3 (unknown) if a certificate file does not exist -- Marcel Pennewiss
+#  - Add a "-d" option to specify a directory or file mask pattern -- Marcel Pennewiss
 #
 # Version 3.29
 #  - Add the openssl -servername flag if it shows up in help.
@@ -170,7 +171,7 @@
 #  Version 1.0
 #      Initial Release
 #
-# Last Updated: 01-05-2016
+# Last Updated: 20-10-2016
 #
 # Purpose: 
 #  ssl-cert-check checks to see if a digital certificate in X.509 format
@@ -250,6 +251,7 @@ OPENSSL=$(which openssl)
 PRINTF=$(which printf)
 SED=$(which sed)
 MKTEMP=$(which mktemp)
+FIND=$(which find)
 
 # Try to find a mail client
 if [ -f /usr/bin/mailx ]
@@ -442,11 +444,12 @@ set_returncode()
 usage() 
 {
     echo "Usage: $0 [ -e email address ] [ -x days ] [-q] [-a] [-b] [-h] [-i] [-n] [-v]"
-    echo "       { [ -s common_name ] && [ -p port] } || { [ -f cert_file ] } || { [ -c certificate file ] }" 
+    echo "       { [ -s common_name ] && [ -p port] } || { [ -f cert_file ] } || { [ -c cert file ] } || { [ -d cert dir ] }"
     echo ""
     echo "  -a                : Send a warning message through E-mail"
     echo "  -b                : Will not print header"
     echo "  -c cert file      : Print the expiration date for the PEM or PKCS12 formatted certificate in cert file"
+    echo "  -d cert directory : Print the expiration date for the PEM or PKCS12 formatted certificates in cert directory"
     echo "  -e E-mail address : E-mail address to send expiration notices"
     echo "  -f cert file      : File with a list of FQDNs and ports"
     echo "  -h                : Print this screen"
@@ -648,13 +651,14 @@ check_file_status() {
 #################################
 ### Start of main program
 #################################
-while getopts abinv:e:f:c:hk:p:s:t:qx:V option
+while getopts abinv:e:f:c:d:hk:p:s:t:qx:V option
 do
     case "${option}"
     in
         a) ALARM="TRUE";;
         b) NOHEADER="TRUE";;
         c) CERTFILE=${OPTARG};;
+        d) CERTDIRECTORY=${OPTARG};;
         e) ADMIN=${OPTARG};;
         f) SERVERFILE=$OPTARG;;
         h) usage
@@ -690,11 +694,11 @@ then
     exit 1
 fi
 
-### Check to make sure a grep utility is available
-if [ ! -f ${GREP} ]
+### Check to make sure a grep and find utility is available
+if [ ! -f ${GREP} ] || [ ! -f ${FIND} ]
 then
-    echo "ERROR: The grep binary does not exist in ${GREP} ."
-    echo "FIX: Please modify the \${GREP} variable in the program header."
+    echo "ERROR: Unable to locate the greb and find binary."
+    echo "FIX: Please modify the \${GREP} and \${FIND} variables in the program header."
     exit 1
 fi
 
@@ -783,6 +787,14 @@ elif [ "${CERTFILE}" != "" ]
 then
     print_heading
     check_file_status ${CERTFILE} "FILE"  "${CERTFILE}"
+
+### Check to see if the certificates in CERTDIRECTORY are about to expire
+elif [ "${CERTDIRECTORY}" != "" ] && (${FIND} -L ${CERTDIRECTORY} -type f > /dev/null 2>&1)
+then
+    print_heading
+    for FILE in `${FIND} -L ${CERTDIRECTORY} -type f`; do
+        check_file_status ${FILE} "FILE" "${FILE}"
+    done
 
 ### There was an error, so print a detailed usage message and exit
 else
